# monitoring/promtail-config.yml

server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Scrape log từ tất cả các container Docker
  - job_name: containers
    docker_sd_configs: # Sử dụng docker_sd_configs
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        filters: # Thêm bộ lọc để chỉ lấy container từ network mong muốn
          - name: network
            values: ["mlops-session-service_app-network"]
    relabel_configs:
      # Lấy label từ Docker và gán cho log stream
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'logstream'
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        target_label: 'service'

  # Scrape log từ file hệ thống (syslog) - Giữ nguyên phần này
  - job_name: syslog
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/syslog
